rootProject.name = "DistributeAsyncExecutor"

//
include("asyncexecutor-core")
//
include("asyncexecutor-communicator")
//
include("asyncexecutor-communicator-api")
//
include("asyncexecutor-communicator-springcloud")
//
include("asyncexecutor-communicator-dubbo")
//
include("asyncexecutor-communicator-grpc")
//
include("asyncexecutor-model")
//
include("asyncexecutor-memory-api")
//
include("asyncexecutor-memory-mysql")
//
include("asyncexecutor-agent-api")
//
include("asyncexecutor-context")
//
include("asyncexecutor-agent-springcloud")
//
include("asyncexecutor-agent-dubbo")
include("asyncexecutor-agent-api-logic")
